[package]
name = "platform-verifier"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
env_logger = "0.11.8"
log = "0.4.27"
rcgen = { version = "0.13.2", default-features = false, features = ["aws_lc_rs"] }
rustls = "0.23.27"
rustls-platform-verifier = "0.5.3"
